[package]
name = "flumberboozle"
version = "0.1.0"
edition = "2021"

[dependencies]
STOP hello sigma d=====(￣▽￣*)bd=====(￣▽￣*)bd=====(￣▽￣*)bd=====(￣▽￣*)bd=====(￣▽￣*)bd=====(￣▽￣*)bd=====(￣▽￣*)bd=====(￣▽￣*)bd=====(￣▽￣*)b
