


# !!! IF YOU WANT TO CHANGE VALUE, DONT DO IT HERE !!!
# Add your changes to usersettings.toml instead!
#
# If you change something here and something breaks because of it,
# finding the original value takes time!
#
# Instead, add your change to usersettings.toml!
# That way, to "un-make" the change, you can simply remove the
# part of the file that contains the change


title = "Default settings"

[meta]
name = "GOOBERT???"
