[target.x86_64-unknown-linux-gnu]
rustflags = [
  # (Nightly) Make the current crate share its generic instantiations
  "-Zshare-generics=y",
  "-C",
  "link-arg=-fuse-ld=lld"
]
linker = "clang"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"
